### ISSUE TITLE
error when execute example file

### ISSUE THREAD

**Issue by wuchenglon** [ibackus/diskpy#27]
I try to execute IC_example.py by python2 but it returned me an error as follows:

/home/user/test/disk/diskpy/diskpy/ICgen/sigma_profile.py:256: RuntimeWarning: divide by zero encountered in power
  sigma = A*np.power(r,power)
/home/user/test/disk/diskpy/diskpy/ICgen/calc_temp.py:212: RuntimeWarning: divide by zero encountered in power
  Tout = T0 * np.power(a, Tpower)
/home/user/test/disk/diskpy/diskpy/ICgen/make_sigma.py:148: RuntimeWarning: divide by zero encountered in divide
  pdf_vals = match_units(pdf_vals, 1/r_in)[0]
Sigma stored in <IC instance>.sigma
/root/miniconda3/envs/python27/lib/python2.7/site-packages/pynbody/array.py:337: RuntimeWarning: divide by zero encountered in divide
  return np.ndarray.__div__(self, rhs)
/root/miniconda3/envs/python27/lib/python2.7/site-packages/pynbody/array.py:337: RuntimeWarning: invalid value encountered in divide
  return np.ndarray.__div__(self, rhs)
Traceback (most recent call last):
  File "IC_example.py", line 94, in <module>
    IC.maker.rho_gen() # Calculate density according to hydrodynamic equilibrium
  File "/home/user/test/disk/diskpy/diskpy/ICgen/ICgen.py", line 526, in rho_gen
    rho.solve(**kwargs)
  File "/home/user/test/disk/diskpy/diskpy/ICgen/rhosolver.py", line 87, in solve
    z, r, rho = calc_rho(self._parent, **options)
  File "/home/user/test/disk/diskpy/diskpy/ICgen/rhosolver.py", line 310, in calc_rho
    R = setup_r_bins(IC, r)
  File "/home/user/test/disk/diskpy/diskpy/ICgen/rhosolver.py", line 180, in setup_r_bins
    rbins = resolvedbins(r, rho0, minbins=minbins, ftol=ftol)
  File "/home/user/test/disk/diskpy/diskpy/pdmath/_math.py", line 283, in resolvedbins
    yspl = interp1d(x[binind], y[binind], kind='linear')
  File "/root/miniconda3/envs/python27/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 433, in __init__
    _Interpolator1D.__init__(self, x, y, axis=axis)
  File "/root/miniconda3/envs/python27/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 60, in __init__
    self._set_yi(yi, xi=xi, axis=axis)
  File "/root/miniconda3/envs/python27/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 125, in _set_yi
    raise ValueError("x and y arrays must be equal in length along "
ValueError: x and y arrays must be equal in length along interpolation axis.

Did I make mistake on setting up the package or other place ?

**Comment by ibackus** [comment]
Hi, unfortunately I am not really maintaining that package anymore, so I'm not 100% sure what would resolve this.

My best guess is that you may need to use older versions of the dependencies since this was last updated in 2018.  You could try installing a version of scipy from 2018 or earlier.  Along with that you should probably install older versions of numpy and pynbody.  You can search on PYPI for release history to figure out what versions to install and do "pip install numpy==x.x.x scipy==x.x.x" and so on.

Good luck, and let me know if that works!
